# Generated by Django 6.0.7 on 2026-07-19 14:31

import apps.orders.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=apps.orders.models.generate_order_number, editable=False, max_length=32, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال\u200cشده'), ('delivered', 'تحویل داده\u200cشده'), ('cancelled', 'لغوشده'), ('failed', 'پرداخت ناموفق')], default='pending_payment', max_length=20, verbose_name='وضعیت')),
                ('receiver_full_name', models.CharField(max_length=150, verbose_name='نام گیرنده')),
                ('receiver_phone', models.CharField(max_length=11, verbose_name='تلفن گیرنده')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس کامل')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('items_total', models.PositiveIntegerField(default=0, verbose_name='جمع قیمت کالاها (تومان)')),
                ('shipping_cost', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال (تومان)')),
                ('discount_total', models.PositiveIntegerField(default=0, verbose_name='مجموع تخفیف (تومان)')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ نهایی قابل\u200cپرداخت (تومان)')),
                ('customer_note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام محصول (در لحظه خرید)')),
                ('unit_price', models.PositiveIntegerField(verbose_name='قیمت واحد (در لحظه خرید)')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
    ]
