# Generated by Django 6.0.7 on 2026-07-26 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_receiver_phone'),
        ('store', '0003_rename_store_produ_product_9c1e21_idx_store_produ_product_b7cdb9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.productvariant', verbose_name='تنوع محصول (رنگ/سایز)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='برچسب تنوع (در لحظه خرید)'),
        ),
    ]
