# Generated by Django 6.0.7 on 2026-07-29 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_shippingsettings_id_alter_shippingtariffrow_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotificationPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='شماره موبایل به\u200cصورت ۱۱ رقمی، مثلاً 09121234567', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید به فرمت 09xxxxxxxxx باشد.', regex='^09\\d{9}$')], verbose_name='شماره تلفن مدیر')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='توضیح (اختیاری)')),
                ('is_active', models.BooleanField(default=True, help_text='در صورت غیرفعال بودن، پیامک اطلاع\u200cرسانی سفارش به این شماره ارسال نمی\u200cشود.', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
            ],
            options={
                'verbose_name': 'شماره اطلاع\u200cرسانی مدیر',
                'verbose_name_plural': 'شماره\u200cهای اطلاع\u200cرسانی مدیر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, help_text='پس از تحویل بسته به اداره پست، این کد توسط ادمین ثبت می\u200cشود و پیامک اطلاع\u200cرسانی به مشتری ارسال می\u200cگردد.', max_length=50, verbose_name='کد رهگیری پستی'),
        ),
    ]
