# Generated by Django 6.0.7 on 2026-08-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_savedaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receiver_full_name',
        ),
        migrations.RemoveField(
            model_name='savedaddress',
            name='receiver_full_name',
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_first_name',
            field=models.CharField(blank=True, max_length=75, verbose_name='نام گیرنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_last_name',
            field=models.CharField(blank=True, max_length=75, verbose_name='نام خانوادگی گیرنده'),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='receiver_first_name',
            field=models.CharField(blank=True, max_length=75, verbose_name='نام گیرنده'),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='receiver_last_name',
            field=models.CharField(blank=True, max_length=75, verbose_name='نام خانوادگی گیرنده'),
        ),
    ]
