# Generated by Django 6.0.7 on 2026-08-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_receiver_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام روش ارسال')),
                ('code', models.SlugField(help_text='مثلاً pishtaz یا tipax', max_length=100, unique=True, verbose_name='کد روش ارسال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('estimated_delivery_time', models.CharField(blank=True, help_text='مثلاً ۲ تا ۴ روز کاری', max_length=100, verbose_name='زمان تقریبی تحویل')),
                ('extra_cost_per_kg', models.PositiveIntegerField(default=0, help_text='اگر وزن سفارش از بیشترین سقف تعرفه بیشتر شود، این مبلغ به ازای هر کیلوگرم اضافه محاسبه می\u200cشود.', verbose_name='هزینه هر کیلوگرم مازاد (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='shippingtariffrow',
            options={'ordering': ['shipping_method_id', 'max_weight_grams'], 'verbose_name': 'ردیف تعرفه ارسال', 'verbose_name_plural': 'تعرفه\u200cهای وزنی ارسال'},
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام روش ارسال در لحظه سفارش'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_weight_grams',
            field=models.PositiveIntegerField(default=0, verbose_name='وزن کل سفارش (گرم)'),
        ),
        migrations.AlterField(
            model_name='shippingtariffrow',
            name='max_weight_grams',
            field=models.PositiveIntegerField(verbose_name='سقف وزن (گرم)'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.shippingmethod', verbose_name='روش ارسال'),
        ),
        migrations.AddField(
            model_name='shippingtariffrow',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_rows', to='orders.shippingmethod', verbose_name='روش ارسال'),
        ),
        migrations.AddConstraint(
            model_name='shippingtariffrow',
            constraint=models.UniqueConstraint(fields=('shipping_method', 'max_weight_grams'), name='unique_shipping_method_weight_limit'),
        ),
    ]
