# Generated by Django 6.0.7 on 2026-08-02 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_shippingmethod_alter_shippingtariffrow_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingtariffrow',
            name='shipping_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_rows', to='orders.shippingmethod', verbose_name='روش ارسال'),
        ),
    ]
