# Generated by Django 6.0.7 on 2026-07-26 11:39

import apps.accounts.managers
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(db_index=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید به فرمت 09xxxxxxxxx باشد.', regex='^09\\d{9}$')], verbose_name='شماره تلفن')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='تایید شماره تلفن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی ادمین')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید به فرمت 09xxxxxxxxx باشد.', regex='^09\\d{9}$')], verbose_name='شماره تلفن')),
                ('code_hash', models.CharField(max_length=128, verbose_name='کد (هش\u200cشده)')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده\u200cشده')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش\u200cهای ناموفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کد یک\u200cبارمصرف',
                'verbose_name_plural': 'کدهای یک\u200cبارمصرف',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'is_used'], name='accounts_ot_phone_n_aabe5e_idx')],
            },
        ),
    ]
