# Generated by Django 6.0.7 on 2026-07-24 00:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('color_name', models.CharField(max_length=50, verbose_name='نام رنگ')),
                ('color_code', models.CharField(blank=True, help_text='مثال: #FF0000', max_length=7, verbose_name='کد رنگ (Hex)')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='سایز / مشخصه اضافی')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='کد کالا (SKU)')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)')),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت با تخفیف (تومان)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='تصویر تنوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تنوع محصول',
                'verbose_name_plural': 'تنوع\u200cهای محصول',
                'ordering': ['color_name', 'size'],
            },
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ لایک')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='store.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_products', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لایک محصول',
                'verbose_name_plural': 'لایک\u200cهای محصول',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('body', models.TextField(max_length=2000, verbose_name='متن نظر')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تاییدشده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر محصول',
                'verbose_name_plural': 'نظرات محصول',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='store.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز محصول',
                'verbose_name_plural': 'امتیازهای محصول',
            },
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'color_name'], name='store_produ_product_5f3a10_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color_name', 'size'), name='unique_product_color_size'),
        ),
        migrations.AddConstraint(
            model_name='productlike',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_product_like'),
        ),
        migrations.AddIndex(
            model_name='productcomment',
            index=models.Index(fields=['product', 'is_approved'], name='store_produ_product_9c1e21_idx'),
        ),
        migrations.AddConstraint(
            model_name='productrating',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_product_rating'),
        ),
    ]
