# Generated by Django 6.0.7 on 2026-07-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variant_like_comment_rating'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productcomment',
            new_name='store_produ_product_b7cdb9_idx',
            old_name='store_produ_product_9c1e21_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='store_produ_product_302780_idx',
            old_name='store_produ_product_5f3a10_idx',
        ),
    ]
