# Generated by Django 6.0.7 on 2026-07-27 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productvariant_weight_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='موجودی انبار'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام رنگ'),
        ),
    ]
