# Generated by Django 6.0.7 on 2026-08-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_stock_alter_productvariant_color_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_value', models.PositiveBigIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'شمارنده SKU',
                'verbose_name_plural': 'شمارنده SKU',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True, verbose_name='کد کالا (SKU)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True, verbose_name='کد کالا (SKU)'),
        ),
    ]
