# Generated by Django 6.0.7 on 2026-09-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_variant_size_to_design_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='توضیحات سئو'),
        ),
    ]
