# Generated by Django 6.0.7 on 2026-09-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_type',
            field=models.CharField(choices=[('none', 'بدون تنوع'), ('color', 'رنگ'), ('design', 'طرح'), ('color_design', 'رنگ و طرح')], default='none', help_text='اگر محصول تنوع ندارد «بدون تنوع» را انتخاب کنید. برای محصولاتی مثل خودکار رنگ و برای محصولاتی مثل دفتر با جلدهای مختلف طرح را انتخاب کنید.', max_length=20, verbose_name='نوع تنوع'),
        ),
    ]
