# Generated by Django 6.0.7 on 2026-07-26 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('message_type', models.CharField(choices=[('request', 'درخواست'), ('complaint', 'انتقاد'), ('suggestion', 'پیشنهاد'), ('other', 'سایر')], default='request', max_length=20, verbose_name='نوع پیام')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, max_length=11, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='موضوع')),
                ('body', models.TextField(max_length=3000, verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('in_progress', 'در حال بررسی'), ('answered', 'پاسخ داده\u200cشده'), ('closed', 'بسته\u200cشده')], default='new', max_length=20, verbose_name='وضعیت پیگیری')),
                ('admin_note', models.TextField(blank=True, help_text='فقط برای استفاده داخلی تیم پشتیبانی است و به کاربر نمایش داده نمی\u200cشود.', verbose_name='یادداشت / پاسخ ادمین')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام تماس با ما',
                'verbose_name_plural': 'پیام\u200cهای تماس با ما',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='contact_con_status_fa3e24_idx'), models.Index(fields=['message_type'], name='contact_con_message_83810e_idx')],
            },
        ),
    ]
