# Generated by Django 6.0.7 on 2026-07-26 11:45

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0003_rename_store_produ_product_9c1e21_idx_store_produ_product_b7cdb9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مقاله',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای مقاله',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='نام تگ')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='اسلاگ')),
                ('excerpt', models.CharField(blank=True, max_length=500, verbose_name='خلاصه')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن مقاله')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='تصویر شاخص')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('scheduled', 'زمان\u200cبندی\u200cشده'), ('published', 'منتشرشده'), ('archived', 'بایگانی\u200cشده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ انتشار')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مقاله ویژه')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد بازدید')),
                ('reading_time_minutes', models.PositiveSmallIntegerField(default=1, editable=False, verbose_name='زمان مطالعه (دقیقه)')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='عنوان سئو')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='توضیحات سئو')),
                ('author', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('related_products', models.ManyToManyField(blank=True, related_name='related_articles', to='store.product', verbose_name='محصولات مرتبط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articles.articlecategory', verbose_name='دسته\u200cبندی')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='articles.tag', verbose_name='تگ\u200cها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ لایک')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='articles.article', verbose_name='مقاله')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لایک مقاله',
                'verbose_name_plural': 'لایک\u200cهای مقاله',
                'constraints': [models.UniqueConstraint(fields=('article', 'user'), name='unique_article_like')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('content', models.TextField(max_length=2000, verbose_name='متن نظر')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article', verbose_name='مقاله')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='articles.comment', verbose_name='پاسخ به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['article', 'is_approved'], name='articles_co_article_e979df_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='articles_ar_status_7759bd_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='articles_ar_categor_ef2274_idx'),
        ),
    ]
