# Generated by Django 6.0.7 on 2026-07-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(help_text='فقط برای مدیریت در پنل است و به کاربر نمایش داده نمی\u200cشود.', max_length=150, verbose_name='عنوان (داخلی)')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر بنر (وب / دسکتاپ)')),
                ('mobile_image', models.ImageField(blank=True, help_text='اختیاری - اگر خالی بماند، همان تصویر اصلی در اپ موبایل هم استفاده می\u200cشود.', null=True, upload_to='banners/mobile/', verbose_name='تصویر بنر (موبایل)')),
                ('position', models.CharField(choices=[('home_slider', 'اسلایدر صفحه اصلی'), ('home_middle', 'میانی صفحه اصلی'), ('category_top', 'بالای صفحه دسته\u200cبندی'), ('app_popup', 'پاپ\u200cآپ اپلیکیشن')], default='home_slider', max_length=20, verbose_name='جایگاه نمایش')),
                ('link_url', models.CharField(blank=True, help_text='آدرس یا مسیری که با ضربه\u200cزدن روی بنر باز می\u200cشود (داخلی یا خارجی)', max_length=500, verbose_name='لینک مقصد')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع نمایش')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان نمایش')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'ordering': ['position', 'order', '-created_at'],
                'indexes': [models.Index(fields=['position', 'is_active'], name='banner_bann_positio_594e62_idx')],
            },
        ),
    ]
