# Generated by Django 6.0.7 on 2026-07-26 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_orderitem_variant_orderitem_variant_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('gateway', models.CharField(choices=[('sizpay', 'سیزپی'), ('sepehr', 'بانک سپهر (صادرات)')], max_length=20, verbose_name='درگاه پرداخت')),
                ('authority', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='کد تراکنش')),
                ('payment_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک پرداخت')),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='شماره مرجع')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('card_pan', models.CharField(blank=True, max_length=20, verbose_name='شماره کارت')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payment_pay_status_124d3d_idx'), models.Index(fields=['authority'], name='payment_pay_authori_8e0a58_idx'), models.Index(fields=['ref_id'], name='payment_pay_ref_id_3b7b58_idx'), models.Index(fields=['created_at'], name='payment_pay_created_671024_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('order',), name='unique_success_payment_per_order')],
            },
        ),
    ]
